# Generated by Django 4.2.6 on 2023-11-07 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
