# Generated by Django 4.2.6 on 2023-11-11 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_sensor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='iot.sensor'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
